
- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  tasks:
    
    - name: Command
      shell: "ansible-galaxy collection list"
      register: salida
      
    - name: Command
      debug:
       var: salida

