- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: all
  become: true
  tasks:
  
    - name: Command2
      shell: "ansible-galaxy install community.general --ignore-errors"
      register: salida2
      delegate_to: localhost
      
    - name: Salida2
      debug:
        var: salida2
         
    - name: Include task list in play
      ansible.builtin.include_tasks:
       file: xml.yml
      ignore_errors: true

      




