

- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  tasks:
    - name: Command
      shell: "ansible-galaxy collection install community.general"
      register: salida


