

- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  tasks:
    - name: Define el intérprete de Python
      command: whoami
      regiser: salida
      
    - name: Define el intérprete de Python
      debug: whoami
        var: salida
      
