

- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  tasks:
    - name: Define el intérprete de Python
      command: ansible-galaxy collection install community.general
      register: salida
      
    - name: Define el intérprete de Python
      debug: 
        var: salida
      
