- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  tasks:
  
    - name: Command2
      shell: "ansible-galaxy collection list"
      register: salida2
      
    - name: Salida2
      debug:
        var: salida2
         
    - name: Include task list in play
      ansible.builtin.include_tasks:
       file: xml.yml
      ignore_errors: true

      




