- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  tasks:
  
    - name: Command1
      shell: "ls /root"
      register: salida1
      
    - name: Salida1
      debug:
        var: salida1
      

      




