

- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  collections:
    - community.general
  tasks:
  
    - name: Command1
      shell: "ansible-galaxy collection list"
      register: salida1
      
    - name: Salida1
      debug:
        var: salida1
      
    - name: Install1
      shell: "ansible-galaxy collection install community.general"
      register: salida
      
    - name: Command2
      shell: "ansible-galaxy collection list"
      register: salida2
      
    - name: Salida2
      debug:
        var: salida2
      



