

- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  tasks:
    - name: Define el intérprete de Python
      command: pip3 list
      register: salida
      
    - name: Salida
      debug:
        var: salida
