

- name: Ejemplo de tarea con definición de intérprete de Python
  hosts: localhost
  become: true
  collections:
    - community.general
  tasks:
    - name: Command
      shell: "ansible-galaxy collection install community.general"
      register: salida
      
    - name: Add a 'phonenumber' element to the 'business' element
      xml:
        path: /foo/bar.xml
        xpath: /business/phonenumber
        value: 555-555-1234


